import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl } from '@angular/forms';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-delhi-refit-seven',
  templateUrl: './delhi-refit-seven.component.html',
  styleUrls: ['./delhi-refit-seven.component.scss']
})
export class DelhiRefitSevenComponent implements OnInit {
  delhiRefitSevenForm: any;
  apiUrl = environment.apiUrl + 'delhi-refit-seven';
  delhiRefitSevenData: any;


  constructor(private fb: FormBuilder, private http: HttpClient) {
    this.delhiRefitSevenForm = this.fb.group({
      BMA_PUMP_Occa: new FormControl(""),
      BMA_PUMP_Date: new FormControl(""),
      rev_osm_raw_water_1: new FormControl(""),
      rev_osm_raw_water_2: new FormControl(""),
      rev_osm_raw_water_3: new FormControl(""),
      rev_osm_raw_water_4: new FormControl(""),
      rev_osm_high_disc_1: new FormControl(""),
      rev_osm_high_disc_2: new FormControl(""),
      rev_osm_high_disc_3: new FormControl(""),
      rev_osm_high_disc_4: new FormControl(""),
      rev_osm_vs60_1: new FormControl(""),
      rev_osm_vs60_2: new FormControl(""),
      rev_osm_vs60_3: new FormControl(""),
      rev_osm_vs60_4: new FormControl(""),
      rev_osm_high_press_1: new FormControl(""),
      rev_osm_high_press_2: new FormControl(""),
      rev_osm_high_press_3: new FormControl(""),
      rev_osm_high_press_4: new FormControl(""),
      rev_osm_brine_pipe_1: new FormControl(""),
      rev_osm_brine_pipe_2: new FormControl(""),
      rev_osm_brine_pipe_3: new FormControl(""),
      rev_osm_brine_pipe_4: new FormControl(""),
      rev_osm_shut_off_1: new FormControl(""),
      rev_osm_shut_off_2: new FormControl(""),
      rev_osm_shut_off_3: new FormControl(""),
      rev_osm_shut_off_4: new FormControl(""),
      rev_osm_pure_water_1: new FormControl(""),
      rev_osm_pure_water_2: new FormControl(""),
      rev_osm_pure_water_3: new FormControl(""),
      rev_osm_pure_water_4: new FormControl(""),
      rev_osm_5TDO_raw_water_5: new FormControl(""),
      rev_osm_5TDO_raw_water_7: new FormControl(""),
      rev_osm_5TDO_high_disc_5: new FormControl(""),
      rev_osm_5TDO_high_disc_7: new FormControl(""),
      rev_osm_5TDO_vs60_5: new FormControl(""),
      rev_osm_5TDO_vs60_7: new FormControl(""),
      rev_osm_5TDO_high_press_5: new FormControl(""),
      rev_osm_5TDO_high_press_7: new FormControl(""),
      rev_osm_5TDO_brine_pipe_5: new FormControl(""),
      rev_osm_5TDO_brine_pipe_7: new FormControl(""),
      rev_osm_5TDO_shut_off_5: new FormControl(""),
      rev_osm_5TDO_shut_off_7: new FormControl(""),
      rev_osm_5TDO_pure_water_5: new FormControl(""),
      rev_osm_5TDO_pure_water_7: new FormControl(""),
      rev_osm_5TDO_raw_water_6: new FormControl(""),
      rev_osm_5TDO_raw_water_8: new FormControl(""),
      rev_osm_5TDO_high_disc_6: new FormControl(""),
      rev_osm_5TDO_high_disc_8: new FormControl(""),
      rev_osm_5TDO_vs60_6: new FormControl(""),
      rev_osm_5TDO_vs60_8: new FormControl(""),
      rev_osm_5TDO_high_press_6: new FormControl(""),
      rev_osm_5TDO_high_press_8: new FormControl(""),
      rev_osm_5TDO_brine_pipe_6: new FormControl(""),
      rev_osm_5TDO_brine_pipe_8: new FormControl(""),
      rev_osm_5TDO_shut_off_6: new FormControl(""),
      rev_osm_5TDO_shut_off_8: new FormControl(""),
      rev_osm_5TDO_pure_water_6: new FormControl(""),
      rev_osm_5TDO_pure_water_8: new FormControl(""),
      per_30TPD_IP_inlet_1: new FormControl(""),
      per_30TPD_IP_inlet_2: new FormControl(""),
      per_30TPD_IP_inlet_3: new FormControl(""),
      per_30TPD_IP_inlet_4: new FormControl(""),
      per_30TPD_IP_outlet_1: new FormControl(""),
      per_30TPD_IP_outlet_2: new FormControl(""),
      per_30TPD_IP_outlet_3: new FormControl(""),
      per_30TPD_IP_outlet_4: new FormControl(""),
      per_30TPD_IR_inlet_1: new FormControl(""),
      per_30TPD_IR_inlet_2: new FormControl(""),
      per_30TPD_IR_inlet_3: new FormControl(""),
      per_30TPD_IR_inlet_4: new FormControl(""),
      per_30TPD_IR_outlet_1: new FormControl(""),
      per_30TPD_IR_outlet_2: new FormControl(""),
      per_30TPD_IR_outlet_3: new FormControl(""),
      per_30TPD_IR_outlet_4: new FormControl(""),
      per_30TPD_IR5_HP_suct_1: new FormControl(""),
      per_30TPD_IR5_HP_suct_2: new FormControl(""),
      per_30TPD_IR5_HP_suct_3: new FormControl(""),
      per_30TPD_IR5_HP_suct_4: new FormControl(""),
      per_30TPD_IR5_HP_disc_1: new FormControl(""),
      per_30TPD_IR5_HP_disc_2: new FormControl(""),
      per_30TPD_IR5_HP_disc_3: new FormControl(""),
      per_30TPD_IR5_HP_disc_4: new FormControl(""),
      per_30TPD_IR4_permeate_disc_1: new FormControl(""),
      per_30TPD_IR4_permeate_disc_2: new FormControl(""),
      per_30TPD_IR4_permeate_disc_3: new FormControl(""),
      per_30TPD_IR4_permeate_disc_4: new FormControl(""),
      per_30TPD_permeate_flow_disc_1: new FormControl(""),
      per_30TPD_permeate_flow_disc_2: new FormControl(""),
      per_30TPD_permeate_flow_disc_3: new FormControl(""),
      per_30TPD_permeate_flow_disc_4: new FormControl(""),
      per_30TPD_sea_water_disc_1: new FormControl(""),
      per_30TPD_sea_water_disc_2: new FormControl(""),
      per_30TPD_sea_water_disc_3: new FormControl(""),
      per_30TPD_sea_water_disc_4: new FormControl(""),
      RO_plant_time_1: new FormControl(""),
      RO_plant_feed_press_PI331_time_1: new FormControl(""),
      RO_plant_feed_press_PI333_time_1: new FormControl(""),
      RO_plant_permeate_PR_1: new FormControl(""),
      RO_plant_concentrate_1: new FormControl(""),
      RO_plant_electrolyte_1: new FormControl(""),
      RO_plant_flow_FI332_1: new FormControl(""),
      RO_plant_flow_FI380_1: new FormControl(""),
      RO_plant_FIS_330_1: new FormControl(""),
      RO_plant_conductivity_1: new FormControl(""),
      RO_plant_time_2: new FormControl(""),
      RO_plant_feed_press_PI331_time_2: new FormControl(""),
      RO_plant_feed_press_PI333_time_2: new FormControl(""),
      RO_plant_permeate_PR_2: new FormControl(""),
      RO_plant_concentrate_2: new FormControl(""),
      RO_plant_electrolyte_2: new FormControl(""),
      RO_plant_flow_FI332_2: new FormControl(""),
      RO_plant_flow_FI380_2: new FormControl(""),
      RO_plant_FIS_330_2: new FormControl(""),
      RO_plant_conductivity_2: new FormControl(""),
      RO_plant_time_3: new FormControl(""),
      RO_plant_feed_press_PI331_time_3: new FormControl(""),
      RO_plant_feed_press_PI333_time_3: new FormControl(""),
      RO_plant_permeate_PR_3: new FormControl(""),
      RO_plant_concentrate_3: new FormControl(""),
      RO_plant_electrolyte_3: new FormControl(""),
      RO_plant_flow_FI332_3: new FormControl(""),
      RO_plant_flow_FI380_3: new FormControl(""),
      RO_plant_FIS_330_3: new FormControl(""),
      RO_plant_conductivity_3: new FormControl(""),
      RO_plant_time_4: new FormControl(""),
      RO_plant_feed_press_PI331_time_4: new FormControl(""),
      RO_plant_feed_press_PI333_time_4: new FormControl(""),
      RO_plant_permeate_PR_4: new FormControl(""),
      RO_plant_concentrate_4: new FormControl(""),
      RO_plant_electrolyte_4: new FormControl(""),
      RO_plant_flow_FI332_4: new FormControl(""),
      RO_plant_flow_FI380_4: new FormControl(""),
      RO_plant_FIS_330_4: new FormControl(""),
      RO_plant_conductivity_4: new FormControl(""),
      RO_plant_No_7_time_1: new FormControl(""),
      RO_plant_No_7_feed_press_PI331_time_1: new FormControl(""),
      RO_plant_No_7_feed_press_PI333_time_1: new FormControl(""),
      RO_plant_No_7_permeate_PR_1: new FormControl(""),
      RO_plant_No_7_concentrate_1: new FormControl(""),
      RO_plant_No_7_electrolyte_1: new FormControl(""),
      RO_plant_No_7_flow_FI332_1: new FormControl(""),
      RO_plant_No_7_flow_FI380_1: new FormControl(""),
      RO_plant_No_7_FIS_330_1: new FormControl(""),
      RO_plant_No_7_conductivity_1: new FormControl(""),
      RO_plant_No_7_time_2: new FormControl(""),
      RO_plant_No_7_feed_press_PI331_time_2: new FormControl(""),
      RO_plant_No_7_feed_press_PI333_time_2: new FormControl(""),
      RO_plant_No_7_permeate_PR_2: new FormControl(""),
      RO_plant_No_7_concentrate_2: new FormControl(""),
      RO_plant_No_7_electrolyte_2: new FormControl(""),
      RO_plant_No_7_flow_FI332_2: new FormControl(""),
      RO_plant_No_7_flow_FI380_2: new FormControl(""),
      RO_plant_No_7_FIS_330_2: new FormControl(""),
      RO_plant_No_7_conductivity_2: new FormControl(""),
      RO_plant_No_7_time_3: new FormControl(""),
      RO_plant_No_7_feed_press_PI331_time_3: new FormControl(""),
      RO_plant_No_7_feed_press_PI333_time_3: new FormControl(""),
      RO_plant_No_7_permeate_PR_3: new FormControl(""),
      RO_plant_No_7_concentrate_3: new FormControl(""),
      RO_plant_No_7_electrolyte_3: new FormControl(""),
      RO_plant_No_7_flow_FI332_3: new FormControl(""),
      RO_plant_No_7_flow_FI380_3: new FormControl(""),
      RO_plant_No_7_FIS_330_3: new FormControl(""),
      RO_plant_No_7_conductivity_3: new FormControl(""),
      RO_plant_No_7_time_4: new FormControl(""),
      RO_plant_No_7_feed_press_PI331_time_4: new FormControl(""),
      RO_plant_No_7_feed_press_PI333_time_4: new FormControl(""),
      RO_plant_No_7_permeate_PR_4: new FormControl(""),
      RO_plant_No_7_concentrate_4: new FormControl(""),
      RO_plant_No_7_electrolyte_4: new FormControl(""),
      RO_plant_No_7_flow_FI332_4: new FormControl(""),
      RO_plant_No_7_flow_FI380_4: new FormControl(""),
      RO_plant_No_7_FIS_330_4: new FormControl(""),
      RO_plant_No_7_conductivity_4: new FormControl(""),
      RO_plant_No_7_time_5: new FormControl(""),
      RO_plant_No_7_feed_press_PI331_time_5: new FormControl(""),
      RO_plant_No_7_feed_press_PI333_time_5: new FormControl(""),
      RO_plant_No_7_permeate_PR_5: new FormControl(""),
      RO_plant_No_7_concentrate_5: new FormControl(""),
      RO_plant_No_7_electrolyte_5: new FormControl(""),
      RO_plant_No_7_flow_FI332_5: new FormControl(""),
      RO_plant_No_7_flow_FI380_5: new FormControl(""),
      RO_plant_No_7_FIS_330_5: new FormControl(""),
      RO_plant_No_7_conductivity_5: new FormControl(""),
      fuel_trans_pipe_sys: new FormControl(""),
      fuel_trans_prime_pump: new FormControl(""),
      fuel_trans_end_cover: new FormControl(""),
      fuel_trans_valve_pos: new FormControl(""),
      fuel_trans_open_pos: new FormControl(""),
      fuel_trans_deck_closed: new FormControl(""),
      fuel_trans_switch_on: new FormControl(""),
      fuel_trans_10min_prd: new FormControl(""),
      fuel_trans_Aft_tanks: new FormControl(""),
      fuel_trans_pump_working: new FormControl(""),
      fuel_trans_TL_15: new FormControl(""),
      check_off_centrifuge_pump_1: new FormControl(""),
      check_off_centrifuge_pump_2: new FormControl(""),
      check_off_centrifuge_fuel_1: new FormControl(""),
      check_off_centrifuge_fuel_2: new FormControl(""),
      check_off_therm_pump_suc_1: new FormControl(""),
      check_off_therm_pump_disc_1: new FormControl(""),
      check_off_therm_pump_suc_2: new FormControl(""),
      check_off_therm_pump_disc_2: new FormControl(""),
      check_off_therm_sep_suc_1: new FormControl(""),
      check_off_therm_sep_disc_2: new FormControl(""),
      check_off_therm_sep_suc_2: new FormControl(""),
      check_off_fO_tank_stor_1: new FormControl(""),
      check_off_fO_tank_stor_2: new FormControl(""),
      check_off_fO_tank_stor_3: new FormControl(""),
      check_off_fO_tank_stor_4: new FormControl(""),
      check_off_fO_tank_stor_22: new FormControl(""),
      check_off_fO_tank_fuel_oil_1_2: new FormControl(""),
      check_off_ffO_tank_fuel_oil_3_4: new FormControl(""),
      check_off_suff_light: new FormControl(""),
      check_off_comm_moto: new FormControl(""),
      check_off_test_area: new FormControl(""),
      check_off_pipe_clamps: new FormControl(""),
      check_off_talley_plate: new FormControl(""),
      check_off_fire_CNAL: new FormControl(""),
      check_off_stor_tank_1: new FormControl(""),
      check_off_stor_tank_2: new FormControl(""),
      check_off_stor_tank_3: new FormControl(""),
      check_off_stor_tank_4: new FormControl(""),
      check_off_stor_tank_22: new FormControl(""),
      check_off_fuel_oil_1_2: new FormControl(""),
      check_off_fuel_oil_3_4: new FormControl(""),
      fuel_trans_ppip_compen: new FormControl(""),
      fuel_trans_pip_flange: new FormControl(""),
      fuel_trans_pip_gasket: new FormControl(""),
      fuel_trans_pip_adap: new FormControl(""),
      fuel_trans_pip_strain_pump_1: new FormControl(""),
      fuel_trans_pip_strain_pump_2: new FormControl(""),
      fuel_trans_pip_feed_pump_1: new FormControl(""),
      fuel_trans_pip_feed_pump_2: new FormControl(""),
      fuel_trans_pip_integrity_check: new FormControl(""),
      fuel_trans_pip_supp_clamps: new FormControl(""),
      fuel_trans_valves_suc_pump_1: new FormControl(""),
      fuel_trans_valves_suc_pump_2: new FormControl(""),
      fuel_trans_valves_sep_1: new FormControl(""),
      fuel_trans_valves_sep_2: new FormControl(""),
      fuel_trans_valves_disc_pump_1: new FormControl(""),
      fuel_trans_valves_disc_pump_2: new FormControl(""),
      fuel_trans_valves_sep_feed_pump_1: new FormControl(""),
      fuel_trans_valves_sep_feed_pump_2: new FormControl(""),
      fuel_trans_valves_def_tank_1: new FormControl(""),
      fuel_trans_valves_def_tank_2: new FormControl(""),
      fuel_trans_valves_def_tank_3: new FormControl(""),
      fuel_trans_valves_def_tank_4: new FormControl(""),
      fuel_trans_valves_tank5_22: new FormControl(""),
      fuel_trans_valves_oil_tank_1_2: new FormControl(""),
      fuel_trans_valves_oil_tank_3_4: new FormControl(""),
      fuel_trans_valves_FWD_AK100: new FormControl(""),
      fuel_trans_valves_port_drum: new FormControl(""),
      fuel_trans_valves_drum_space: new FormControl(""),
      fuel_trans_valves_AFT_deck: new FormControl(""),
      fuel_trans_valves_bal_19: new FormControl(""),
      fuel_trans_valves_tank_1_2: new FormControl(""),
      fuel_trans_valves_tank_3_4: new FormControl(""),
      fuel_trans_valves_feed_pump_1: new FormControl(""),
      fuel_trans_valves_feed_pump_2: new FormControl(""),
      fuel_trans_valves_sep_inlet: new FormControl(""),
      fuel_trans_soun_tube: new FormControl(""),
      fuel_trans_gasket_renewed: new FormControl(""),
      fuel_trans_inst_press_pump_suc_1: new FormControl(""),
      fuel_trans_inst_press_pump_disc_1: new FormControl(""),
      fuel_trans_inst_press_pump_suc_2: new FormControl(""),
      fuel_trans_inst_press_pump_disc_2: new FormControl(""),
      fuel_trans_inst_press_feed_suc_1: new FormControl(""),
      fuel_trans_inst_press_feed_disc_1: new FormControl(""),
      fuel_trans_inst_press_feed_suc_2: new FormControl(""),
      fuel_trans_inst_press_feed_disc_2: new FormControl(""),
      fuel_trans_inst_press_other_gauges: new FormControl(""),
      fuel_trans_inst_sensor_stor_tank_1: new FormControl(""),
      fuel_trans_inst_sensor_stor_tank_2: new FormControl(""),
      fuel_trans_inst_sensor_stor_tank_3: new FormControl(""),
      fuel_trans_inst_sensor_stor_tank_4: new FormControl(""),
      fuel_trans_inst_sensor_stor_tank_22: new FormControl(""),
      fuel_trans_inst_sensor_stor_tank_1_2: new FormControl(""),
      fuel_trans_inst_sensor_stor_tank_3_4: new FormControl(""),
      fuel_trans_inst_sensor_gauge_line: new FormControl(""),
      fuel_trans_found_pump: new FormControl(""),
      fuel_trans_found_feed_pump: new FormControl(""),
      fuel_trans_found_sep: new FormControl(""),
      fuel_trans_mount_phy_cond: new FormControl(""),
      fuel_trans_mount_atten: new FormControl(""),
      fuel_trans_mount_OEM_doc: new FormControl(""),
      fuel_trans_func_barge_ship: new FormControl(""),
      fuel_trans_func_goose_neck: new FormControl(""),
      fuel_trans_func_port_stbd: new FormControl(""),
    });

  }

  ngOnInit(): void {
    this.getDelhiRefitSeven();
  }

  getDelhiRefitSeven(): void {
    this.http.get(this.apiUrl + "/trial-id=16").subscribe(data => {
      console.log(data);
      this.delhiRefitSevenData = data;
      this.delhiRefitSevenForm.patchValue(this.delhiRefitSevenData);

    });
  }

  onSubmit() {
    const formData = this.delhiRefitSevenForm.value;
    this.http.post(this.apiUrl, formData).subscribe(() => {
      this.getDelhiRefitSeven(); // Refresh list
      console.log(this.delhiRefitSevenForm.value);  // { name: '...', email: '...', age: '...' }
    });

  }

}
