import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl } from '@angular/forms';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-delhi-refit-nine',
  templateUrl: './delhi-refit-nine.component.html',
  styleUrls: ['./delhi-refit-nine.component.scss']
})
export class DelhiRefitNineComponent implements OnInit {
  delhiRefitNineForm: any;
  delhiRefitNineData: any;
  apiUrl = environment.apiUrl + 'delhi-refit-nine';

  constructor(private fb:FormBuilder, private http: HttpClient) { 
this.delhiRefitNineForm = this.fb.group({
bilge_out_pump_no_1: new FormControl(""),
bilge_out_pump_no_2: new FormControl(""),
salvage_pump_no_1: new FormControl(""),
salvage_pump_no_2: new FormControl(""),
salvage_pump_no_3: new FormControl(""),
salvage_pump_no_4: new FormControl(""),
salvage_pump_no_5: new FormControl(""),
salvage_pump_no_6: new FormControl(""),
salvage_pump_no_7: new FormControl(""),
salvage_pump_no_8: new FormControl(""),
salvage_pump_no_9: new FormControl(""),
salvage_pump_no_10: new FormControl(""),
salvage_pump_no_11: new FormControl(""),
salvage_pump_no_12: new FormControl(""),
bilge_out_press_vacc: new FormControl(""),
bilge_out_sys_drawings: new FormControl(""),
bilge_out_flex_flang: new FormControl(""),
bilge_out_suff_loc: new FormControl(""),
bilge_out_rubb_inserts: new FormControl(""),
bilge_out_talley_plates: new FormControl(""),
bilge_sal_pipe_clear_obs: new FormControl(""),
bilge_sal_prim_unit: new FormControl(""),
bilge_sal_driv_end_cover: new FormControl(""),
bilge_sal_pos_indic: new FormControl(""),
bilge_sal_open_pos: new FormControl(""),
bilge_sal_corr_rot: new FormControl(""),
syst_trial_bellow_conn: new FormControl(""),
syst_trial_flange_conn: new FormControl(""),
syst_trial_gasket: new FormControl(""),
syst_trial_adapter: new FormControl(""),
syst_trial_suc_strainer_1: new FormControl(""),
syst_trial_suc_strainer_2: new FormControl(""),
syst_trial_integrity_check: new FormControl(""),
syst_trial_supp_conn: new FormControl(""),
valves_bilge_suc_pump_no_1: new FormControl(""),
valves_bilge_suc_pump_no_2: new FormControl(""),
valves_bilge_disc_pump_no_1: new FormControl(""),
valves_bilge_disc_pump_no_2: new FormControl(""),
valves_Salvage_suc_pump_no_1: new FormControl(""),
valves_Salvage_suc_pump_no_2: new FormControl(""),
valves_Salvage_suc_pump_no_3: new FormControl(""),
valves_Salvage_suc_pump_no_4: new FormControl(""),
valves_Salvage_suc_pump_no_5: new FormControl(""),
valves_Salvage_suc_pump_no_6: new FormControl(""),
valves_Salvage_suc_pump_no_7: new FormControl(""),
valves_Salvage_suc_pump_no_8: new FormControl(""),
valves_Salvage_suc_pump_no_9: new FormControl(""),
valves_Salvage_suc_pump_no_10: new FormControl(""),
valves_Salvage_suc_pump_no_11: new FormControl(""),
valves_Salvage_suc_pump_no_12: new FormControl(""),
valves_Salvage_disc_pump_no_1: new FormControl(""),
valves_Salvage_disc_pump_no_2: new FormControl(""),
valves_Salvage_disc_pump_no_3: new FormControl(""),
valves_Salvage_disc_pump_no_4: new FormControl(""),
valves_Salvage_disc_pump_no_5: new FormControl(""),
valves_Salvage_disc_pump_no_6: new FormControl(""),
valves_Salvage_disc_pump_no_7: new FormControl(""),
valves_Salvage_disc_pump_no_8: new FormControl(""),
valves_Salvage_disc_pump_no_9: new FormControl(""),
valves_Salvage_disc_pump_no_10: new FormControl(""),
valves_Salvage_disc_pump_no_11: new FormControl(""),
valves_Salvage_disc_pump_no_12: new FormControl(""),
valves_Salvage_board_pump_no_1: new FormControl(""),
valves_Salvage_board_pump_no_2: new FormControl(""),
valves_Salvage_board_pump_no_3: new FormControl(""),
valves_Salvage_board_pump_no_4: new FormControl(""),
valves_Salvage_board_pump_no_5: new FormControl(""),
valves_Salvage_board_pump_no_6: new FormControl(""),
valves_Salvage_board_pump_no_7: new FormControl(""),
valves_Salvage_board_pump_no_8: new FormControl(""),
valves_Salvage_board_pump_no_9: new FormControl(""),
valves_Salvage_board_pump_no_10: new FormControl(""),
valves_Salvage_board_pump_no_11: new FormControl(""),
valves_Salvage_board_pump_no_12: new FormControl(""),
valves_educ_pow_no_1: new FormControl(""),
valves_educ_pow_no_2: new FormControl(""),
valves_educ_pow_no_3: new FormControl(""),
valves_educ_pow_no_4: new FormControl(""),
valves_educ_pow_no_5: new FormControl(""),
valves_educ_pow_no_6: new FormControl(""),
valves_educ_pow_no_7: new FormControl(""),
valves_educ_pow_no_8: new FormControl(""),
valves_educ_pow_no_9: new FormControl(""),
valves_educ_pow_no_10: new FormControl(""),
valves_educ_pow_no_11: new FormControl(""),
valves_educ_pow_no_12: new FormControl(""),
valves_educ_pow_no_13: new FormControl(""),
valves_educ_pow_no_14: new FormControl(""),
valves_educ_pow_no_15: new FormControl(""),
valves_educ_pow_no_16: new FormControl(""),
valves_educ_pow_no_17: new FormControl(""),
bilge_pump_found_pump_1: new FormControl(""),
bilge_pump_found_pump_2: new FormControl(""),
bilge_pump_found_salv_pump_1: new FormControl(""),
bilge_pump_found_salv_pump_2: new FormControl(""),
bilge_pump_found_salv_pump_3: new FormControl(""),
bilge_pump_found_salv_pump_4: new FormControl(""),
bilge_pump_found_salv_pump_5: new FormControl(""),
bilge_pump_found_salv_pump_6: new FormControl(""),
bilge_pump_found_salv_pump_7: new FormControl(""),
bilge_pump_found_salv_pump_8: new FormControl(""),
bilge_pump_found_salv_pump_9: new FormControl(""),
bilge_pump_found_salv_pump_10: new FormControl(""),
bilge_pump_found_salv_pump_11: new FormControl(""),
bilge_pump_found_salv_pump_12: new FormControl(""),
bilge_out_mount_phy_cond: new FormControl(""),
bilge_out_mount_atten: new FormControl(""),
bilge_out_mount_OEM_doc: new FormControl(""),
bilge_out_ballast_rubb_inserts: new FormControl(""),
bilge_out_ballast_suff_loc: new FormControl(""),
bilge_out_ballast_talley_plates: new FormControl(""),
syst_trial_ballas_flange_conn: new FormControl(""),
syst_trial_ballas_gasket: new FormControl(""),
syst_trial_ballas_adapter: new FormControl(""),
syst_trial_ballas_integrity_check: new FormControl(""),
syst_trial_ballas_supp_conn: new FormControl(""),
syst_trial_ballas_iso_valve_1: new FormControl(""),
syst_trial_ballas_ball_valve_1: new FormControl(""),
syst_trial_ballas_iso_valve_2: new FormControl(""),
syst_trial_ballas_ball_valve_2: new FormControl(""),
syst_trial_ballas_iso_valve_3: new FormControl(""),
syst_trial_ballas_ball_valve_3: new FormControl(""),
syst_trial_ballas_iso_valve_4: new FormControl(""),
syst_trial_ballas_ball_valve_4: new FormControl(""),
syst_trial_ballas_iso_valve_5: new FormControl(""),
syst_trial_ballas_ball_valve_5: new FormControl(""),
syst_trial_ballas_iso_valve_6: new FormControl(""),
syst_trial_ballas_ball_valve_6: new FormControl(""),
syst_trial_chill_ATU_pump_1: new FormControl(""),
syst_trial_chill_ATU_pump_2: new FormControl(""),
syst_trial_chill_ATU_pump_3: new FormControl(""),
syst_trial_chill_ATU_pump_4: new FormControl(""),
syst_trial_chill_ATU_pump_5: new FormControl(""),
syst_trial_chill_ATU_pump_6: new FormControl(""),
syst_trial_chill_ATU_HE_inlet: new FormControl(""),
syst_trial_chill_ATU_HE_outlet: new FormControl(""),
syst_trial_chill_press_therm_suc: new FormControl(""),
syst_trial_chill_press_therm_disc: new FormControl(""),
syst_trial_chill_press_inst_acc: new FormControl(""),
syst_trial_chill_disc_flanges: new FormControl(""),
syst_trial_chill_water_pipe: new FormControl(""),
syst_trial_chill_clamp_inst: new FormControl(""),
syst_trial_chill_suff_oper_loc: new FormControl(""),
syst_trial_chill_cold_lagg: new FormControl(""),
syst_trial_chill_talley_plate: new FormControl(""),
syst_trial_chill_press_purg_drain: new FormControl(""),
syst_trial_pip_bellow_conn: new FormControl(""),
syst_trial_pip_flange_conn: new FormControl(""),
syst_trial_pip_gasket: new FormControl(""),
syst_trial_pip_adapter: new FormControl(""),
syst_trial_pip_suc_strainer_1: new FormControl(""),
syst_trial_pip_suc_strainer_2: new FormControl(""),
syst_trial_pip_integrity_check: new FormControl(""),
syst_trial_pip_supp_conn: new FormControl(""),
sys_trial_suc_pump_no_1: new FormControl(""),
sys_trial_suc_pump_no_2: new FormControl(""),
sys_trial_suc_pump_no_3: new FormControl(""),
sys_trial_suc_pump_no_4: new FormControl(""),
sys_trial_suc_pump_no_5: new FormControl(""),
sys_trial_suc_pump_no_6: new FormControl(""),
sys_trial_disc_pump_no_1: new FormControl(""),
sys_trial_disc_pump_no_2: new FormControl(""),
sys_trial_disc_pump_no_3: new FormControl(""),
sys_trial_disc_pump_no_4: new FormControl(""),
sys_trial_disc_pump_no_5: new FormControl(""),
sys_trial_disc_pump_no_6: new FormControl(""),
sys_trial_disc_isolat_valves: new FormControl(""),
sys_trial_disc_tank_fill_1: new FormControl(""),
sys_trial_disc_tank_out_1: new FormControl(""),
sys_trial_disc_tank_purg_1: new FormControl(""),
sys_trial_disc_tank_fill_2: new FormControl(""),
sys_trial_disc_tank_out_2: new FormControl(""),
sys_trial_disc_tank_purg_2: new FormControl(""),
sys_trial_disc_tank_exp_fill_2: new FormControl(""),
sys_trial_disc_tank_out_3: new FormControl(""),
sys_trial_disc_tank_purg_3: new FormControl(""),
sys_trial_disc_HE_inlet: new FormControl(""),
sys_trial_disc_HE_outlet: new FormControl(""),
sys_trial_disc_purg_valves: new FormControl(""),
sys_trial_disc_HUMSA_sonar_post: new FormControl(""),
sys_trial_disc_stbd_inlet: new FormControl(""),
sys_trial_disc_port_inlet: new FormControl(""),
sys_trial_disc_stbd_outlet: new FormControl(""),
sys_trial_disc_port_outlet: new FormControl(""),
sys_trial_exp_tank_sight_glass: new FormControl(""),
sys_trial_exp_tank_paint_scheme: new FormControl(""),
sys_trial_exp_tank_insp_door: new FormControl(""),
sys_trial_inst_press_gauge: new FormControl(""),
sys_trial_inst_gauge_lines: new FormControl(""),
sys_trial_found_pump_no_1: new FormControl(""),
sys_trial_found_pump_no_2: new FormControl(""),
sys_trial_found_pump_no_3: new FormControl(""),
sys_trial_found_pump_no_4: new FormControl(""),
sys_trial_found_pump_no_5: new FormControl(""),
sys_trial_found_pump_no_6: new FormControl(""),
sys_trial_found_exp_tank_1: new FormControl(""),
sys_trial_found_exp_tank_2: new FormControl(""),
sys_trial_found_exp_tank_3: new FormControl(""),
sys_trial_mount_phy_cond: new FormControl(""),
sys_trial_mount_atten: new FormControl(""),
sys_trial_mount_OEM_doc: new FormControl(""),
        })
  }

  ngOnInit(): void {
    this.getDelhiRefitNine()
  }

    getDelhiRefitNine(): void {
    this.http.get(this.apiUrl+ "/trial-id=1").subscribe(data => {
      console.log(data);
      this.delhiRefitNineData = data;
      this.delhiRefitNineForm.patchValue(this.delhiRefitNineData);

    });
  }

  onSubmit() {
    const formData = this.delhiRefitNineForm.value;
    this.http.post(this.apiUrl, formData).subscribe(() => {
      this.getDelhiRefitNine(); // Refresh list
  console.log(this.delhiRefitNineForm.value);  // { name: '...', email: '...', age: '...' }
});

}



}
